import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The docs sidebar is split into two top-level buckets so the left nav stays
 * organized as the docs grow (team decision, 2026-08):
 *
 *   User Guide       — everything an end user needs
 *   Technical Guide  — everything a developer / operator needs
 *
 * Each bucket pulls in whole folders via `autogenerated`, so new pages added to
 * a folder still appear automatically (no need to edit this file). Ordering
 * WITHIN a folder still comes from each page's `sidebar_position` / the folder's
 * `_category_.json`; ordering BETWEEN the folders comes from the array order here.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'User Guide',
      collapsible: true,
      collapsed: false,
      items: [
        'intro', // Overview
        {type: 'autogenerated', dirName: 'start'},
        {type: 'autogenerated', dirName: 'guide'},
        {type: 'autogenerated', dirName: 'faq'},
      ],
    },
    {
      type: 'category',
      label: 'Technical Guide',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'technical'},
        {type: 'autogenerated', dirName: 'dev'},
        {type: 'autogenerated', dirName: 'reference'},
        {type: 'autogenerated', dirName: 'migration'},
      ],
    },
  ],
};

export default sidebars;
