import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Technical / Knowledge instance (served at /Knowledge).
const sidebars: SidebarsConfig = {
  knowledgeSidebar: [
    {type: 'autogenerated', dirName: '.'}

  ],
};

export default sidebars;
