import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Technical / Knowledge instance (served at /Knowledge).
const sidebars: SidebarsConfig = {
  knowledgeSidebar: [
    {type: 'autogenerated', dirName: 'technical'},
    {type: 'autogenerated', dirName: 'dev'},
    {type: 'autogenerated', dirName: 'reference'},
    {type: 'autogenerated', dirName: 'migration'},
  ],
};

export default sidebars;
