import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// User Guide instance (served at /guide). Whole-folder autogeneration, so new
// pages appear automatically; order within a folder comes from sidebar_position
// / _category_.json.
const sidebars: SidebarsConfig = {
  guideSidebar: [
    'intro', // Overview
    {type: 'autogenerated', dirName: 'start'},
    {type: 'autogenerated', dirName: 'handbook'},
    {type: 'autogenerated', dirName: 'faq'},
  ],
};

export default sidebars;
