import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// User Guide instance (served at /guide).
//
// Two products at the top level, Kite-docs style: QDay Chain first, then
// QPass (agentic payments). Existing folders are referenced in place, so no
// page URL changes; each folder still autogenerates its own pages, ordered by
// sidebar_position / _category_.json.
const sidebars: SidebarsConfig = {
  guideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'QDay Chain',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Get Started',
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'start'}],
        },
        {
          type: 'category',
          label: 'Handbook',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Handbook',
            description: 'Everyday tasks on QDay — wallets, staking, swap, and the bridge.',
            slug: '/handbook',
          },
          items: [{type: 'autogenerated', dirName: 'handbook'}],
        },
        'faq/index',
      ],
    },
    {
      type: 'category',
      label: 'QPass',
      collapsed: false,
      link: {type: 'doc', id: 'qpass/index'},
      items: ['qpass/identity-model', 'qpass/setup', 'qpass/payment-flows'],
    },
  ],
};

export default sidebars;
