import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// User Guide instance (served at /guide). Whole-folder autogeneration, so new
// pages appear automatically; order within a folder comes from sidebar_position
// / _category_.json.
const sidebars: SidebarsConfig = {
  // Autogenerate from the guide/ root so start/, handbook/, faq/ become
  // nested sidebar categories instead of a flat list of pages.
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
